### ISSUE TITLE
Does not work via SSH?

### ISSUE THREAD

**Issue by yllekz** [narugit/smctemp#10]
Hello, I'm not sure if this is a profile or variable issue, but if I try to run smctemp remotely via an ssh session, I get a ``command not found`` error:

```
ssh me@mymac 'smctemp -c'
(me@mymac) Password:
zsh:1: command not found: smctemp
```

Is there something I need to add to ``~/.zshrc`` to make this work? It works just fine in Terminal directly on the system.

**Comment by narugit** [comment]
@yllekz Could you show me the result of following commands?
```
$ ssh me@mymac
(in-your-PC via SSH )$ which smctemp
(in-your-PC via SSH )$ echo $PATH
```

### In your PC in directly login
```
$ which smctemp
$ echo $PATH
```

**Comment by yllekz** [comment]
SSH:
``smcsetup not found`` and ``/usr/bin:/bin:/usr/sbin:/sbin`` respectively

Directly:
``smcsetup not found`` and ``/Users/me/.rd/bin:/Users/me/miniconda/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin`` respectively

**Comment by narugit** [comment]
@yllekz 
not smcsetup but smctemp.
From your PATH, smctemp may be searchable.
How about `ssh me@mymac 'source ~/.zshrc && echo $PATH`?

**Comment by yllekz** [comment]
Ah whoops sorry about that.

SSH:
``smctemp not found`` and ``/usr/bin:/bin:/usr/sbin:/sbin``


Directly:
``/usr/lcoal/bin/smctemp``and ``/Users/me/.rd/bin:/Users/me/miniconda/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin`` respectively

**Comment by narugit** [comment]
@yllekz 
I don't know why your PATH variable is different with ssh and directly login.
In your use, I suppose that you can use `ssh me@mymac 'PATH=/usr/local/bin:$PATH smctemp -c'` or `ssh me@mymac 'export PATH=/usr/local/bin:$PATH && smctemp -c'`.
Does these commands work?

**Comment by narugit** [comment]
@yllekz 
From your command output, it seems that the `command not found` error occurs when executing the command over SSH because `/usr/local/bin` directory is not included in the PATH variable in that specific context.
This appears to be a configuration issue on the user's PC rather than a problem with this repository. Since it is not directly related to the project, I believe it would be appropriate to close this issue.

If you encounter any other difficulties or have additional questions, please don't hesitate to reach out.

**Comment by yllekz** [comment]
Sorry for the delay, yes your workaround worked, thanks.
