### ISSUE TITLE
Apple M2 Max Support (Macbook Pro 2023 14")

### ISSUE THREAD

**Issue by joshuataylor** [narugit/smctemp#11]
Hi!

Thanks again for this great tool.

The new "Apple M2 Max", which Macbook Pros can come with, seems to report the temperature wrong, where it's `/10`?.

`smctemp -c`
> 3.4

`uname -m`
> arm64

`sysctl -in sysctl.proc_translated`
> 0

`smctemp -l | grep -i "t[cp]0"`
```sh
  Tp00  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp01  [flt ]  6.7 (bytes: 66 66 D6 40)
  Tp02  [flt ]  8.4 (bytes: CD CC 06 41)
  Tp04  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp05  [flt ]  4.6 (bytes: 89 41 94 40)
  Tp06  [flt ]  5.3 (bytes: 66 66 AA 40)
  Tp08  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp09  [flt ]  6.7 (bytes: 66 66 D6 40)
  Tp0A  [flt ]  8.4 (bytes: CD CC 06 41)
  Tp0C  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp0D  [flt ]  4.6 (bytes: 89 41 94 40)
  Tp0E  [flt ]  5.3 (bytes: 66 66 AA 40)
  Tp0W  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp0X  [flt ]  6.7 (bytes: 66 66 D6 40)
  Tp0Y  [flt ]  8.4 (bytes: CD CC 06 41)
  Tp0a  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp0b  [flt ]  4.6 (bytes: 89 41 94 40)
  Tp0c  [flt ]  5.3 (bytes: 66 66 AA 40)
  Tp0e  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp0f  [flt ]  6.7 (bytes: 66 66 D6 40)
  Tp0g  [flt ]  8.4 (bytes: CD CC 06 41)
  Tp0i  [flt ]  0.0 (bytes: 00 00 00 00)
  Tp0j  [flt ]  4.6 (bytes: 89 41 94 40)
  Tp0k  [flt ]  5.3 (bytes: 66 66 AA 40)
  ftP0  [flt ]  6.7 (bytes: 66 66 D6 40)
  ftp0  [flt ]  30.8 (bytes: B0 12 F6 41)
```

`smctemp -c && smctemp -l > smc_out`:

https://gist.github.com/joshuataylor/bb02ed6bad2d9f3bd0fe2e8d478bbd2d

Current workaround: `echo $(($(smctemp -c)*10))` 😁

**Comment by narugit** [comment]
@joshuataylor 
https://github.com/exelban/stats 
This application seems to be able to check CPU temperature with M2.
https://github.com/exelban/stats/blob/b8564ff67fb288b19b2d39d9203e0c2f6082b1e4/Modules/Sensors/values.swift#L359-L368

Could you try to install https://github.com/exelban/stats and give me screenshots like below?
<img width="317" alt="image" src="https://github.com/narugit/smctemp/assets/28133383/44658701-c8c4-4fc5-a60d-57cea80a8d99">
