### ISSUE TITLE
CPU Temp Shows 0.0 | 2023 14", M2 Max (12 Core), Sonoma 14.5

### ISSUE THREAD

**Issue by kyleyannelli** [narugit/smctemp#32]
```
╭─kyannelli::mbp @ ~/smctemp
╰─ » smctemp -c
0.0
╭─kyannelli::mbp @ ~/smctemp
╰─ » smctemp -g
40.3
```

<img width="281" alt="Screenshot 2024-08-11 at 8 10 58 PM" src="https://github.com/user-attachments/assets/d7e4be0d-cfd2-4fca-8466-c0480341a36e">

```
Model Name:	MacBook Pro
  Model Identifier:	Mac14,5
  Model Number:	Z17J000AKLL/A
  Chip:	Apple M2 Max
  Total Number of Cores:	12 (8 performance and 4 efficiency)
  Memory:	32 GB
  System Firmware Version:	10151.121.1
  OS Loader Version:	10151.121.1
  ```
  
  It seems the prior support added for the M2 Max 8 core PR #14 does not work for the 12 core M2 Max.

**Comment by kyleyannelli** [comment]
It looks like the sensor values have changed https://github.com/exelban/stats/blob/e3fb0ae9b369efa33b4e5708a39abc95661cde11/Modules/Sensors/values.swift#L373-L389

**Comment by narugit** [comment]
@kyleyannelli 
Could you give me the result of below command?

```console
$ system_profiler SPHardwareDataType | grep -iv ID
$ smctemp -l
```

**Comment by kyleyannelli** [comment]
Hi @narugit . You have the output of system_profiler above in my initial issue message. 
I've attached the `smctemp -l` output as a text file.
[smctemp_dash_l.out.txt](https://github.com/user-attachments/files/16592599/smctemp_dash_l.out.txt)

**Comment by narugit** [comment]
Hi @kyleyannelli 
I'm sorry, I missed that. Thank you for the attachment.

I've reviewed the output from smctemp -l. 
Could you take a screenshot of the Sensors app at the moment you run the smctemp -l command? 
This way, we can compare the information from both the command-line tool and the GUI app, which will help us with a more accurate analysis.

**Comment by kyleyannelli** [comment]
No need to apologize!

Here's the screenshot and output.
[screenshot_stats_smctemp_dash_l.out.txt](https://github.com/user-attachments/files/16592874/screenshot_stats_smctemp_dash_l.out.txt)
<img width="1512" alt="Screenshot 2024-08-12 at 8 06 04 PM" src="https://github.com/user-attachments/assets/2d5c10a5-c5f0-4b90-8093-389fe83f6690">

**Comment by narugit** [comment]
@kyleyannelli 
Thank you!
I've just remembered that the M2 sensors are a bit strange.

https://github.com/narugit/smctemp/pull/14#issuecomment-1694618157

> It'll return like "36.1" sometimes, then 4.2..

Therefore, we've added the attempt logic to read correct sensor value by adding `-n` option (attempt times).
How about running below command?
`$ smctemp -c -n10`

**Comment by kyleyannelli** [comment]
No such luck. I have a better chance of getting a real result with higher values such as `n50`. However, this makes the runtime for the command much too long. Still with `n50` it seems to be a low chance of getting a proper value.

**Comment by kyleyannelli** [comment]
I also want to reiterate I almost always get a proper value if I run `smctemp -c` after installing or building with `&&`. Even if I build and run the command manually, it does not show this behavior. Only if it is in conjunction via `&&`.
Ex. `sudo make && ./smctemp -c`

**Comment by narugit** [comment]
@kyleyannelli 

> No such luck. I have a better chance of getting a real result with higher values such as `n50`. However, this makes the runtime for the command much too long. Still with `n50` it seems to be a low chance of getting a proper value.

I see.
The stats app does the same thing, getting sensor values at regular intervals and updating only when it gets values in the normal range (10°C~110°C).
https://github.com/exelban/stats/blob/e3fb0ae9b369efa33b4e5708a39abc95661cde11/Modules/Sensors/readers.swift#L124-L125

I guess smctemp is not an app that keeps running in the background, so it might not be a good match.
How about decrease the sleep value of https://github.com/narugit/smctemp/blob/dc5a60700d7501a7fe812cb8e94f26a120adf901/main.cc#L88 and increase the number of attempts?
I don't have M2 Max on hand, so I hope you can find a good value.

**Comment by narugit** [comment]
@kyleyannelli 
>  Even if I build and run the command manually, it does not show this behavior.

Do you mean your manual command works properly?

**Comment by kyleyannelli** [comment]
# Clarification
> @kyleyannelli
> 
> > Even if I build and run the command manually, it does not show this behavior.
> 
> Do you mean your manual command works properly?

Sorry let me demonstrate that better.
Running this (separate commands)
```
$ sudo make clean
$ sudo make
$ ./smctemp -c
```
Will almost always produce incorrect values.

While
```
$ sudo make clean && sudo make && ./smctemp -c
```
Will almost always give me proper values. This doesn't make sense to me as it's compiled. I'm not really sure why the behavior is displaying like this.

# Sleep Time Adjustment
I've set the sleep to 100ms and run with `-n500`. Obviously this consumes a bit more CPU, but nothing of note.

I made a test script to trial how many times the output was 0.0 and over 1000 runs. 
With 100ms sleep and `-n500` it is successful 80% of the time. With the median command run time being ~1 second. Worst case 11 seconds. 

This will have to be good enough as smctemp is the only CLI tool I have. 
I can finally display my CPU temp in my tmux status bar with this 😃.

# Pull Request?
Since I have the m2 12 core efficiency sensors on my branch do you want me to make a PR so you can add them? 
I realized the core count checking logic I added might not matter as invalid values get dropped. So should I adjust it to add all the sensors in m2 regardless of this (eg remove `getLogicalCPUCount`)? Below is a snippet.

```
  int getLogicalCPUCount() {
      int logicalCPUCount = 0;
      size_t bufferLength = sizeof(logicalCPUCount);
      sysctlbyname("hw.logicalcpu", &logicalCPUCount, &bufferLength, nullptr, 0);
      return logicalCPUCount;
  }
  // existing code

  const std::string cpumodel = getCPUModel();
  const int logicalcpucount = getLogicalCPUCount();
  if (cpumodel.find("m3") != std::string::npos) {  // Apple M2
  // exisiting code
  } else if (cpumodel.find("m2") != std::string::npos) {  // Apple M2 8 core
    if (logicalcpucount == 12) { // Apple M2 12 Core
      // Add eff cores
      sensors.emplace_back(static_cast<std::string>(kSensorTp1h));
      sensors.emplace_back(static_cast<std::string>(kSensorTp1t));
      sensors.emplace_back(static_cast<std::string>(kSensorTp1p));
      sensors.emplace_back(static_cast<std::string>(kSensorTp1l));
      // Rest of cores are performance
   }
    // CPU core 1
    sensors.emplace_back(static_cast<std::string>(kSensorTp01));
    // CPU core 2
    sensors.emplace_back(static_cast<std::string>(kSensorTp09));
    // CPU core 3
    sensors.emplace_back(static_cast<std::string>(kSensorTp0f));
    // CPU core 4
    sensors.emplace_back(static_cast<std::string>(kSensorTp0n));
    // CPU core 5
    sensors.emplace_back(static_cast<std::string>(kSensorTp05));
    // CPU core 6
    sensors.emplace_back(static_cast<std::string>(kSensorTp0D));
    // CPU core 7
    sensors.emplace_back(static_cast<std::string>(kSensorTp0j));
    // CPU core 8
    sensors.emplace_back(static_cast<std::string>(kSensorTp0r));
```

Sorry for such a long winded reply. I just wanted to be thorough. Hope it's not too much.

**Comment by narugit** [comment]
@kyleyannelli 
It's puzzling that there’s a difference in the results when using && versus not using it..

The results of your sleep time and retry tuning tests are quite interesting. 
It's surprising that even with a high number of retries, you can still get abnormal values. 
Perhaps we should consider adding hyper attempt feature with -n set to 0, which could lead to an infinite loop, or try with a very large number of retries.

Regarding the pull request, please go ahead. 
As you mentioned, since invalid sensor values are skipped, it seems that the getLogicalCPUCount mechanism might not be necessary.

**Comment by kyleyannelli** [comment]
@narugit Yes, I'm a bit puzzled by the difference in results via `&&` as well. It is really disappointing Apple doesn't give us a good interface for something seemingly trivial.

I can play around with the `-n0` idea later tomorrow. For now, I've made the pull request.

Thank you for your quick responses and willingness to try things out.

**Comment by kyleyannelli** [comment]
@narugit I've played around a bit with the hyper attempt feature. It seems a sleep value of 25ms and 1000 retries will consistently get a value. A sleep value any lower will yield more failure than success.

# Testing
Running the command as such `time for i in {1..10000}; do ./smctemp -c -n1000; done` then dividing the resultant seconds by 10000 to derive the average command time. Using this method I found that it took an average of **0.011 seconds** to run the `./smctemp -c -n1000` command. I ran this trial 2 times and found that the command did not fail once. Therefore, I'm not sure an infinite number of retries would be necessary.

What do you think?

**Comment by narugit** [comment]
@kyleyannelli 
Thank you for sharing the test results. 
Indeed, looking at your case, it seems that setting an appropriate interval is more effective for obtaining stable sensor values than simply increasing the number of trials.
I wonder if there were any cases where the maximum time took a few seconds out of the 10,000 trials?

Since the optimal interval likely depends on hardware factors as well, I think it's a good idea to add option to set the interval within a realistic range (20ms to 1000ms).

**Comment by narugit** [comment]
> Since the optimal interval likely depends on hardware factors as well, I think it's a good idea to add option to set the interval within a realistic range (20ms to 1000ms).

I've created the PR https://github.com/narugit/smctemp/pull/34

**Comment by narugit** [comment]
Hi @kyleyannelli 
I've merged the PR below, so I'll be closing this issue. 
- #34 
- #35  

Thank you for your help with opening the issue and debugging!

As I'm preparing to release via Homebrew, I need some more stars. 
If you don't mind, giving it a star would be greatly appreciated! https://github.com/narugit/smctemp/issues/3#issuecomment-1678582469
