### ISSUE TITLE
Does not return any value on M1 in macOS Ventura

### ISSUE THREAD

**Issue by yllekz** [narugit/smctemp#6]
I followed the install instructions and it loaded just fine but the value is always ``0.0%`` no matter what.

**Comment by narugit** [comment]
@yllekz 
Actually, my mac is also M1 chip with macOS Ventura and it works. 
![image](https://user-images.githubusercontent.com/28133383/220872206-7bddc4bc-8044-4670-b0ea-0be43b9a8e4e.png)

Let me ask some questions. Could you tell me the command result below?
1. 
```console
$ uname -m
```

2. 
```console
$ sysctl -in sysctl.proc_translated
```

3. 
```console
$ smctemp -l | grep -i "t[cp]0"
```

**Comment by yllekz** [comment]
```
me@myMac ~ % uname -m
arm64
me@myMac ~ % sysctl -in sysctl.proc_translated
0
me@myMac ~ % smctemp -l | grep -i "t[cp]0"
  Tc0a  [flt ]  29.5 (bytes: 33 41 EC 41)
  Tc0b  [flt ]  29.5 (bytes: 33 41 EC 41)
  Tc0x  [flt ]  30.9 (bytes: 00 60 F7 41)
  Tc0z  [flt ]  30.9 (bytes: 00 60 F7 41)
  ftP0  [flt ]  37.0 (bytes: 4A 02 14 42)

```

**Comment by narugit** [comment]
@yllekz 
Thank you for checking.
The implementation is based on the sensor information that exists [acidanthera/VirtualSMC/Docs/SMCSensorKeys.txt](https://github.com/acidanthera/VirtualSMC/blob/master/Docs/SMCSensorKeys.txt) and there is no information about the sensors on your PC.
For example, the model identifier of my PC is MacBook Pro18,3, what is the model identifier of your PC?

**Comment by narugit** [comment]
@yllekz 
Now I'm searching the information of your PC's sensors (Tc0a, Tc0b, Tc0x, Tc0z). 
Let me know if you find any info. too :)

**Comment by narugit** [comment]
@yllekz 
Actually, I could not get the information about the sensors (Tc0a, Tc0b, Tc0x, Tc0z). But I can guess the sensor key may show about CPU temperature. It's because the letter start with "T" of "Thermal" or "Temperature".
I can't guarantee the value of the sensor, but you can import the following commits and rebuild the tool for your use.
https://github.com/narugit/smctemp/commit/4ad68e6efb3f23d346bdfffd0195b343e30371cc

**Comment by narugit** [comment]
@yllekz 
Actually, I could not get the information about the sensors (Tc0a, Tc0b, Tc0x, Tc0z). But I can guess the sensor key may show about CPU temperature. It's because the letter start with "T" of "Thermal" or "Temperature".
I can't guarantee the value of the sensor, but you can import the following commits and rebuild the tool for your use.
https://github.com/narugit/smctemp/commit/541ae75e30da6e2089fd5ca8bb99c36f2bc03a80

**Comment by yllekz** [comment]
The Mac I ran this on was an M1 Mac Mini, aka Macmini9,1

**Comment by narugit** [comment]
@yllekz 
Did you try https://github.com/narugit/smctemp/issues/6#issuecomment-1442611244 ?

**Comment by joshuataylor** [comment]
Howdy, thanks for this great tool and the patch!

I've tried the patch and it doesn't return 0.0, but a different value, where as it's running at ~31c.

`smctemp -c`
`12.8`

`uname -m`
`arm64`

`sysctl -in sysctl.proc_translated`
`0`

`smctemp -l | grep -i "t[cp]0"`
```sh
  Tc0a  [flt ]  31.7 (bytes: E2 3E FD 41)
  Tc0b  [flt ]  31.7 (bytes: E2 3E FD 41)
  Tc0x  [flt ]  33.1 (bytes: 00 50 04 42)
  Tc0z  [flt ]  33.1 (bytes: 00 50 04 42)
  ftP0  [flt ]  33.2 (bytes: A5 AE 04 42)
  oTc0  [flt ]  100.0 (bytes: 00 00 C8 42)
  oTp0  [flt ]  5.0 (bytes: 00 00 A0 40)
```

> MacBook Air (M1, 2020)
> 12.6.6 (21G646)

When running `smctemp -c && smctemp -l > smc_out`:
`12.8`

smc_out:
https://gist.github.com/joshuataylor/3e2d6f68f7c02ee82104bd3070db60e1

**Comment by narugit** [comment]
@joshuataylor 
Thank you for checking my patch and attaching your helpful log.
Thanks to your log, I could find bug!
Could you apply below two patches or just checking out to [`feature/use_tc0abxz`](https://github.com/narugit/smctemp/tree/feature/use_tc0abxz) branch?
- https://github.com/narugit/smctemp/commit/541ae75e30da6e2089fd5ca8bb99c36f2bc03a80
- https://github.com/narugit/smctemp/commit/73955d485ead69c2b7725619f788eb4d8c34211f

**Comment by joshuataylor** [comment]
Fantastic! That works, and reports the correct temperature for the M1.

It's super quick too! `0.00s user 0.00s system 47% cpu 0.012 total`!! :tada:

> Also, line 415 of `smctemp.cc` needs a `;` at the end.

**Comment by narugit** [comment]
@joshuataylor 
Thank you for your quick checking!! I'm grad that it works!
> Also, line 415 of smctemp.cc needs a ; at the end.

Oops.. Thank you for pointing out ;) I will fix it and will merge into main branch.

**Comment by yllekz** [comment]
Thanks, works for me now after updating.
